### ISSUE TITLE
explore options for improving HA plot

### ISSUE THREAD

**Issue by beanumber** [bigfour/competitiveness#10]

**Comment by beanumber** [comment]
I added a plot that is simple, and somewhat crowded. But I still it conveys the relevant information in a clearer way. Let me know what you guys think.

**Comment by statsbylopez** [comment]
Love this. Great work. It's a squeeze but it conveys everything we want it to. Also, looks like all of my morning edits to the "Best team win" probability also went through as we pushed and pulled at appropriate times.
