### ISSUE TITLE
factor levels not in same order in all places?

### ISSUE THREAD

**Issue by beanumber** [bigfour/competitiveness#12]
We should try to make the colors correspond to the specific sports consistently throughout the whole paper. In Figure 7, the NHL is purple, but in Figure 5, the NBA is purple. Can we agree on a consistent ordering of the factors early on in the paper? What's wrong with alphabetical?

**Comment by statsbylopez** [comment]
Agree.

Figure 7 matches Figure’s 3 and 4 (the contour plots). Can those colors be done with Figure 5?
