### ISSUE TITLE
BestTeam.Win.Sample.R breaks

### ISSUE THREAD

**Issue by beanumber** [bigfour/competitiveness#13]
Mine breaks here:
```
> nba <- fun.bestwin("nba", betas$nba)
Error in betas.sport[season, week, teams[1], sample(1:4000, 1), sample(1:3,  : 
  subscript out of bounds
> nhl <- fun.bestwin("nhl", betas$nhl)
Error in betas.sport[season, week, teams[1], sample(1:4000, 1), sample(1:3,  : 
  subscript out of bounds
> mlb <- fun.bestwin("mlb", betas$mlb)
Error in betas.sport[season, week, teams[1], sample(1:4000, 1), sample(1:3,  : 
  subscript out of bounds
> nfl <- fun.bestwin("nfl", betas$nfl)
```

I think the way to handle this is for this script to save `cdf.all` as an `.RData` file, and then move the ggplot code into the main `jasa2016.Rnw` file. I'm trying to fix the colors as per #12 but I can't get the script to generate the data necessary to produce the plot. 

Could we get these data from `tidy_betas`? 

@statsbylopez can you investigate?

**Comment by statsbylopez** [comment]
We definitely should not replicate from `tidy_betas` (which only has the _average_ team strength). However, I could save the pre-plot draws and call that into the main `jasa2016.Rnw` file. 

Will do later today

**Comment by beanumber** [comment]
Can you draw from `params.rda`?

**Comment by statsbylopez** [comment]
Not for the team strengths. `params.rda` only has the _sigmas_, _gammas_, and _alpha_sport_

**Comment by beanumber** [comment]
@statsbylopez Can you make it so that `BestWin.Sample.R` creates `bestwin.rda`? I see that you've moved the ggplot code to the main file already. Also, `bestwin.rda` needs to be in the repo.

**Comment by statsbylopez** [comment]
Done and done
