### ISSUE TITLE
missing trace plots not in repository

### ISSUE THREAD

**Issue by beanumber** [bigfour/competitiveness#8]
```
LaTeX Warning: File `figure/MLBtrace.pdf' not found on input line 566.


! Package pdftex.def Error: File `figure/MLBtrace.pdf' not found.
```
@statsbylopez can you add these to the repository? Or, better yet, can you add the code to generate these to the repository?

**Comment by beanumber** [comment]
In the trace plots, can @statsbylopez put more transparency on chains so that the green doesn't just dominate?

**Comment by statsbylopez** [comment]
Fixed (I think). Let me know if the new ones are sufficient
