### ISSUE TITLE
nfl_checks.R doesn't work with bigfour.final.rda

### ISSUE THREAD

**Issue by beanumber** [bigfour/competitiveness#9]
@gjm112 @statsbylopez can one of you look into this? I'm not sure what this script is doing or if it's necessary, but it doesn't work with `bigfour.final.rda`. It's looking for an older version of `bigfour.rda`. Can you confirm that it doesn't matter or update it so that it works?

**Comment by statsbylopez** [comment]
Greg may know better, but it doesn't look like we still need this script
